### ISSUE TITLE
Python dynamic module loading

### ISSUE THREAD

**Issue by johnhoffman** [apache/openwhisk-runtime-python#63]
I'm not sure if this is the appropriate place to ask, but I'm wondering why the Python runtime spawns a subprocess instead of dynamically importing the function.

Did you decide one is better than the other for Python?

**Comment by rabbah** [comment]
hi @johnhoffman sorry for the late reply - if you're still curious there are two version of the python runtime `python3action` and `actionloop-python-v3.7`. The former does what you're suggesting and the latter spawns a process. We have normalized many of the runtimes on the latter mechanism because it allows us to reuse a runtime proxy implemented in go. Performance benchamrks also showed this is still faster than the intra process function execution.
